
#define GRID_HEIGHT 10
#define GRID_WIDTH 16

#define PANEL_CARDS_COUNT 7

#define FIELD_WIDTH 18
#define FIELD_HEIGHT 18

#define MENU_BUTTONS_SXOFFSET 7
#define MENU_BUTTONS_XOFFSET 6
#define MENU_BUTTONS_SYOFFSET 35